/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PowerStorage_constants.h"

namespace PowerStorage {

const PowerStorageConstants g_PowerStorage_constants;

PowerStorageConstants::PowerStorageConstants() {
}

} // namespace

