/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PowerStorage_CONSTANTS_H
#define PowerStorage_CONSTANTS_H

#include "PowerStorage_types.h"

namespace PowerStorage {

class PowerStorageConstants {
 public:
  PowerStorageConstants();

};

extern const PowerStorageConstants g_PowerStorage_constants;

} // namespace

#endif
