#!/usr/bin/env python

import sys
from urlparse import urlparse
from thrift.transport import TTransport
from thrift.transport import TSocket
from thrift.transport import THttpClient
from thrift.protocol import TBinaryProtocol

import PowerStorage
from ttypes import *

if len(sys.argv) < 2:
	print ''
	print 'Usage: '+sys.argv[0]+' function <arg>'
	print ''
	print 'Functions:'
	print '    add <source> <destination> <timestamp>'
	print '    remove <source> <destination>'
	print '    selectone <source> <destination>'
	print '    selectfrom <source>'
	print '    selectto <destination>'
	print ''
	sys.exit(0)

host = 'localhost'
port = 1410

socket = TSocket.TSocket(host, port)
transport = TTransport.TFramedTransport(socket)
protocol = TBinaryProtocol.TBinaryProtocol(transport)
client = PowerStorage.Client(protocol)

transport.open()

if sys.argv[1] == 'add':
	client.add(int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]))
elif sys.argv[1] == 'remove':
	client.remove(int(sys.argv[2]), int(sys.argv[3]))
elif sys.argv[1] == 'selectone':
	edges = client.selectOne(int(sys.argv[2]), int(sys.argv[3]))
	print edges
elif sys.argv[1] == 'selectfrom':
	edges = client.selectFrom(int(sys.argv[2]))
	print edges
elif sys.argv[1] == 'selectto':
	edges = client.selectTo(int(sys.argv[2]))
	print edges
else:
	print 'Wrong function!'

transport.close()
